#include "../includes/writer.hpp"

#include <time.h>

#include <cstring>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>

#include "../includes/graph.hpp"

using namespace std;

void Writer::menu() {
    cout << "\nEnter the functionality you want for the inserted graph: \n"
         << endl;
    cout
        << "(1) Direct Transitive Closure"
        << endl;
    cout << "(2) Indirect Transitive Closure" << endl;
    cout << "(3) Local Clustering Coefficient" << endl;
    cout << "(4) Average Clustering Coefficient" << endl;
    cout << "(5) Shortest Path using Dijkstra's Algorithm" << endl;
    cout << "(6) Shortest Path using Floyd's Algorithm" << endl;
    cout << "(7) Prim's Algorithm" << endl;
    cout << "(8) Kruskal's Algorithm" << endl;
    cout << "(9) Tree generated by Depth-First Search Order" << endl;
    cout << "(10) Graph Output in .dot Format" << endl;
    cout << "(11) Print Adjacency List" << endl;
    cout << "(12) Print Nodes" << endl;
    cout << "-> ";
}
